mutation CompetitionUpdate (
  $id: ID!
  $nom: String,
  $emplacement: String,
  $date: Date,
  $pwd: String,
  $organisateurs: [ID!],
  $challenges: [ChallengeInput!],
  $statut: Boolean,
  $image: Upload
  ) {
	majCompetition (
    id: $id,
    nom: $nom,
    emplacement: $emplacement,
    date: $date,
    pwd: $pwd,
    organisateurs: $organisateurs,
    statut: $statut,
    challenges: $challenges,
    image: $image) {
      id
      nom
      date
      emplacement
      image
      statut
	  }
}
