mutation CompetitionCreer (
  $nom: String!,
  $emplacement: String!,
  $date: Date!,
  $pwd: String!,
  $organisateurs: [ID!]!,
  $statut: Boolean!,
  $image: Upload,
  $challenges: [ChallengeInput!]!
  ) {
	creerCompetition (
    nom: $nom,
    emplacement: $emplacement,
    date: $date,
    pwd: $pwd,
    organisateurs: $organisateurs,
    statut: $statut,
    image: $image,
    challenges: $challenges) {
      id
      nom
      date
      emplacement
      image
      statut
	  }
}
