query competitionCurrent {
  currentCompetition @client {
    id
    nom
    statut
    organisateurs {
      id
    }
    juges {
      user {
        id
      }
      epreuves {
        id
      }
    }
  }
}
