query getCompetition($id: ID!) {
  competition (id: $id) {
    id
    nom
    date
    emplacement
    image
		statut
    organisateurs {
      id
      nom
    }
    challenges {
      id
      epreuve {
        id
        nom
        maxEssais
        unitePrincipale
        erreur
      }
      essais
      statut
    }
    equipes {
      id
      nom
      avatar
      etiquette {
        id
        valeur
      }
      adulte {
        id
        nom
        prenom
        annee
        points
        categorie {
          id
          nom
          genre
        }
        avatar
        scores {
          points
          statut
          marques
          challenge {
            id
            essais
            epreuve {
              id
              nom
              unitePrincipale
              uniteSecondaire
              erreur
            }
          }
        }
      }
      enfant {
        id
        nom
        prenom
        annee
        points
        categorie {
          id
          nom
          genre
        }
        avatar
        scores {
          points
          statut
          marques
          challenge {
            id
            essais
            epreuve {
              id
              nom
              unitePrincipale
              uniteSecondaire
              erreur
            }
          }
        }
      }
      statut
      points
      proprietaire {
        id
        nom
      }
    }
  }
}
