query getEquipe ($id: ID!) {
  equipe (id: $id) {
    id
    nom
    avatar
    statut
    points
    etiquette {
      id
      valeur
    }
    adulte {
      id
      prenom
      nom
      avatar
      annee
      points
      scores {
        id
        points
        marques
        statut
        challenge {
          id
          epreuve {
            id
            nom
            unitePrincipale
          }
        }
      }
      categorie {
        id
        nom
        genre
      }
    }
    enfant {
      id
      prenom
      nom
      avatar
      annee
      points
      categorie {
        id
        nom
      }
      scores {
        id
        points
        marques
        statut
        challenge {
          id
          epreuve {
            id
            nom
            unitePrincipale
          }
        }
      }
      categorie {
        id
        nom
        genre
      }
    }
    proprietaire {
      id
      nom
    }
  }
}
