mutation JugeCreer (
  $competition: ID!,
  $juges:[JugeInput!]!
  ) {
	defineCompetitionJuges (
    competition: $competition,
    juges: $juges
  ) {
    juges {
      id
      user {
        id
        nom
      }
      epreuves {
        id
        nom
      }
    }
  }
}