mutation setResultat (
  $athlete: ID!,
  $resultat: ResultatInput!
  ) {
	athleteResultat (
    athlete: $athlete,
    resultat: $resultat
  ) {
    id
    points
    scores {
      points
      statut
      marques
      challenge {
        id
        essais
        epreuve {
          id
          nom
          unitePrincipale
          uniteSecondaire
          erreur
        }
      }
    }
  }
}
